### ISSUE TITLE
config.plist Incorrect Padding

### ISSUE THREAD

**Issue by PalmJosh** [steelbrain/razer-blade-17-pro-2020-hackintosh#1]
I tried to use your config.plist with GenSMBIOS and it says that this config.plist has incorrect Padding. Same error with the Tool ProperTree.

**Comment by steelbrain** [comment]
Looks like the changes I made to publish it on Github were too harsh :) 
Sorry about that

Fixed in https://github.com/steelbrain/razer-blade-17-pro-2020-hackintosh/commit/c1fa4c446504cc6bafdacbe9cb4b6c0803adf70c

Please try now

**Comment by PalmJosh** [comment]
Thanks, it is working now.
