### ISSUE TITLE
iGPU brightness

### ISSUE THREAD

**Issue by shiecldk** [steelbrain/razer-blade-17-pro-2020-hackintosh#5]
Hi @steelbrain, would you able to get the iGPU brightness adjustment working on OLED? I cannot get it to work on the 2020 15 inch advanced model. A similar problem seems to exist on the 2020 base model:
https://www.tonymacx86.com/threads/razer-blade-15-2020-base-model-igpu-acceleration-i7-10750h.305933/

**Comment by steelbrain** [comment]
HI @astro-lee-k 

Yes, I have working brightness adjustment with OLED. It works like any normal display, no difference

I think the reason it may not be working for you and the people in the thread is that you first need full graphics acceleration, then the display works.

**Comment by shiecldk** [comment]
That's very strange. I think it's already in full graphics acceleration. I'm using the same DeviceProperties and SSDTs. I also found other people have problems with brightness and wake on OLED:
https://www.tonymacx86.com/threads/brightness-control-xps-7590-i7-9750h-uhd-630.280567/

**Comment by steelbrain** [comment]
Well either way, this repository is open source, you can download it and look at what ACPI patches I've added and see if anything is relevant to your setup

Edit: You should also install Hackintool and check the "VDA Decoder" to see if it says "Fully Supported" or something else

**Comment by shiecldk** [comment]
Yes, VDA Decoder says Fully Supported. I suspect it may be a hardware-specific problem. Maybe the 300Hz OLED is different from my 60Hz OLED?

**Comment by steelbrain** [comment]
> Maybe the 300Hz OLED is different from my 60Hz OLED?

I really doubt it. If you want to save time with this, you should also hire https://hackintosh.expert/ to make your config. I hired them and they saved me a lot of time.

Anyway, this isn't a bug so closing but feel free to continue discussion
