### ISSUE TITLE
> Update: AMIBCP version 5.02.0031 can modify the BIOS without the language name error. So you do not have to use the UEFITool editing method.

### ISSUE THREAD

**Issue by RodFer01** [steelbrain/razer-blade-17-pro-2020-hackintosh#8]
> Update: AMIBCP version 5.02.0031 can modify the BIOS without the language name error. So you do not have to use the UEFITool editing method.

Steelbrain, I tried to use this version, but I got a error "18 error : secure flash rom verify fail". Please, do you get the same error? Do you know any workaround here? Thank you, Rodrigo

_Originally posted by @RodFer01 in https://github.com/steelbrain/razer-blade-17-pro-2020-hackintosh/issues/3#issuecomment-969684488_

**Comment by steelbrain** [comment]
This is unrelated to bios editing, and is about bios flashing so I'm closing this thread and replying to the other one.
